version: '3.8'
services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  some-service:
    container_name: some-service
    build:
      context: ./some_service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ENFORCE_DOMAIN=false
      - GF_SECURITY_COOKIE_SAMESITE=disabled
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./configs/grafana.yaml:/etc/grafana/provisioning/datasources/prometheus.yml

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    
volumes:
  prometheus_data: {}